id: IA9B93CC2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T09:05:04+00:00'
last_modified: '2022-06-10T10:56:19.896196+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG11865
  title: འབྲི་གུང་བཀའ་བརྒྱུད་ཀྱི་འདོན་ཆོག་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    15E5:
      image_group_id: I1KG22626
      title: ''
      total_pages: 574
      order: 1
      base_file: 15E5.txt
    48B8:
      image_group_id: I1KG22627
      title: ''
      total_pages: 562
      order: 2
      base_file: 48B8.txt
    AB0F:
      image_group_id: I1KG22628
      title: ''
      total_pages: 600
      order: 3
      base_file: AB0F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
